### ISSUE TITLE
Get exception when attaching volume to container

### ISSUE THREAD

**Issue by cgroschupp** [profitbricks/docker-volume-profitbricks#6]
I get the following exception when i attach a volume to a container (`docker run -ti -v test02:/data alpine sh`):
```
INFO[0237] Getting a Volume
INFO[0237] Getting a Volume
INFO[0237] Mounting Volume: /dev/vdb
2018/08/27 12:28:10 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc420076780)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x69d5a0, 0xc4200100f0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
main.(*Driver).Mount(0xc420076480, 0xc42044a1c8, 0x8, 0xc420362300, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/StackPointCloud/docker-volume-profitbricks/driver.go:308 +0x19e
github.com/StackPointCloud/docker-volume-profitbricks/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func6(0xc42044a1c8, 0x8, 0xc420362300, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/StackPointCloud/docker-volume-profitbricks/vendor/github.com/docker/go-plugins-helpers/volume/api.go:114 +0x9a
github.com/StackPointCloud/docker-volume-profitbricks/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).handleMount.func1(0xa27bc0, 0xc4200d61a0, 0xc4200ba2d0)
        /go/src/github.com/StackPointCloud/docker-volume-profitbricks/vendor/github.com/docker/go-plugins-helpers/volume/api.go:145 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420011800, 0xa27bc0, 0xc4200d61a0, 0xc4200ba2d0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42001f5f0, 0xa27bc0, 0xc4200d61a0, 0xc4200ba2d0)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420076500, 0xa27bc0, 0xc4200d61a0, 0xc4200ba2d0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420076780, 0xa28140, 0xc42001d700)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

I don't understand why the lsblk output is written to the metadata for the volume. And why the lsblk is executed before the disk is attached. Because the disk does not appear 
in the lsblk output when the disk is not attached

When i write the volumeState to the metadata, everything works as usual, see in my branch:
https://github.com/cgroschupp/docker-volume-profitbricks/commit/a0ac513ec6cd59e9762d6df30c53d9c787869d4b

**Comment by edevenport** [comment]
@cgroschupp We are using `lsblk` for volume discovery. When we attach a volume to a server, we need to associate that volume with the device name on the host. As we know, device names are added in order - vda, vdb, vdc. However, this pattern is disrupted once we start detaching and reattaching volumes.

So we are using `lsblk` to get a list of device before attaching a volume, we attach the volume, and then we get the list again. The diff between the two lists will identify the new device name regardless of the naming order.

We did look at the volume deviceNumber in the API, but this does not appear to correlate with any port or ID on the host system.

We have requested a better method for device discovery as `lsblk` has some limitations when it comes to parallel requests. Some other providers set the device hardware vendor ID to something predictable on the host. The device then appears in `/dev/disks/by-id`. Setting this to the volume UUID could address the discovery issue, however, we have no ETA on when something like this will be implemented.

**Comment by cgroschupp** [comment]
@edevenport Thanks for the explanation, but I didn't find this in the source code.

The `getNewLsblk` is executed before the disk is attached and the `result` is written to the metadata without the new disk.

https://github.com/profitbricks/docker-volume-profitbricks/blob/master/driver.go#L153
https://github.com/profitbricks/docker-volume-profitbricks/blob/master/driver.go#L277

**Comment by denza** [comment]
@cgroschupp I am not able to reproduce this issue,but you are right about Lsblk, it is obsolete. We will remove the obsolete code. 

A new logic is located in the method GetDeviceName in utilities.go.  There is a comment in this method that tries to explain new logic.
